### ISSUE TITLE
Dominos bug ?

### ISSUE THREAD

**Issue by Subu0203** [tullamods/Dominos#434] opened 2020-05-23 10:48 UTC
Hello !
I have a problem with the domino addon ..

I sometimes can't click on my icons, in the action bars ...
the info bubble does not even appear and I generally have to look in the corners of the "square" of the button for a place to be able to click, finding my bearings as soon as I see the info bubble.

I also can't find a way to set the option to make the spell bars "red" when we are too far from the target.

I tried to change long and wide but nothing helps

Thanks for your help !

**Comment by Tuller** [comment] 2020-05-24 19:10
Do you have a screenshot of when you cannot click on buttons? If you can get it along with what's on your screen with /fstack that would help.

Making the buttons red is part of another addon, like tullaRange.

**Comment by Subu0203** [comment] 2020-06-01 09:12
![WoWScrnShot_052620_145432](https://user-images.githubusercontent.com/65811776/83394320-af827200-a3f8-11ea-9095-ca831b4e3944.jpg)
![WoWScrnShot_052620_145434](https://user-images.githubusercontent.com/65811776/83394332-b3ae8f80-a3f8-11ea-8c7e-49cd2c1937da.jpg)


impossible to click on the button and we can see that the info bubble does not even appear ...
we do not see the mouse on the screenshot but I have it on the jewelry

**Comment by Subu0203** [comment] 2020-06-01 09:13
`Making the buttons red is part of another addon, like tullaRange.`
thank you =)

**Comment by Tuller** [comment] 2020-06-13 18:44
Finally getting back to this. Were you able to try hovering over the bar with /fstack enabled? I suspect this is caused by another addon you're running.

**Comment by Subu0203** [comment] 2020-06-13 19:08
Hello, great thank you very much
 I don't understand the command mentioned here: / fstack activated?
 I do have other addicts, but none touch the bars module
 I have the impression that a mask that I do not see is active on the bottom of my screen because it generally affects the buttons that are the lowest I use move everything, I was able to scan the quotes in quotes  encounter this problem but there is nothing that could prevent me from clicking
 Because when I use a Shortcut it does not pose any problem I can click on the button via my shortened mouse button I had opted for domino because I had installed Bartender and I had encountered the same problem suddenly I discovered  your involvement is it pleases me much better than Bartender

Thomas Grégoire Tedesco
Rue de Genève 75
1004 Lausanne
+41796275546

Le 13 juin 2020 à 20:44, Jason Greer <notifications@github.com> a écrit :

Finally getting back to this. Were you able to try hovering over the bar with /fstack enabled? I suspect this is caused by another addon you're running.

**Comment by Tuller** [comment] 2020-06-13 19:30
/fstack is a chat command like /dom config. It’ll bring up an overlay that lets you see the names frames under your cursor. That can let me know what’s blocking the dominos buttons from being clickable

**Comment by Lab00Rat** [comment] 2020-06-16 23:46
I have been having a similar issue with the Extra Action Button activity. I lose control over hotkey 5 and sometimes 6 when the EAB is activated. I screenshot the frames. The EAB frame is active in the hotbar when the button becomes available. in combat, the 5 (6) key does not function. 
![EAB Enabled](https://user-images.githubusercontent.com/67029992/84839046-ab15a600-b001-11ea-84a3-d25da490a9e1.jpg)
![EAB - disabled](https://user-images.githubusercontent.com/67029992/84839050-abae3c80-b001-11ea-8963-65044f313b87.jpg)

**Comment by Tuller** [comment] 2020-06-27 21:59
This should be fixed in 8.3.11

**Closed** 2020-07-09 15:47 UTC
Labels: ☠️ bug
