### ISSUE TITLE
Mage Portals not working on action bars also Hunter pet abilities are not working either

### ISSUE THREAD

**Issue by Caliredneck69** [tullamods/Dominos#695] opened 2022-12-02 21:24 UTC
**When reporting an issue, please try to reproduce the issue with just Dominos and Dominos_Config running.** Dominos reuses a good chunk of the stock UI, and other popular addons, like Move Anything, like to take control of those parts, too.

**Addon Version**
You can get this via running `/dominos version` in game

**World of Warcraft Version**
For example, Classic, Retail, PTR, Beta.

**Comment by Tuller** [comment] 2022-12-02 23:43
This is a duplicate of #641

**Closed by Tuller** 2022-12-02 23:43 UTC
