### ISSUE TITLE
WoW Freezes with 2 battle net accounts

### ISSUE THREAD

**Issue by nylathak** [tullamods/Dominos#758] opened 2023-05-19 19:29 UTC
So I have been freezing for like 30 seconds every time im logged on with my first account (WoW1) when the second account(WoW2) completes the loading screen. Only using Dominos on first account, second one no addons.

Using latesting Dominos version.

WoW retail.

**Comment by Tuller** [comment] 2023-05-20 15:16
This is a duplicate of #754

**Closed by Tuller** 2023-05-20 15:16 UTC
Labels: bug
