### ISSUE TITLE
[Dragonflight] Edit Mode Related Execution Path Taint

### ISSUE THREAD

**Issue by Tuller** [tullamods/Dominos#701] opened 2022-12-10 16:40 UTC
There are multiple instances reported of actions not working in combat, typically after encountering a loading screen. These are all likely sourced from taint introduced via the new Edit Mode UI.

* #698 
* #690 
* #694
* #658 
* #703 
* #707 
* #744

**Comment by hollo6** [comment] 2023-01-10 11:46
Always happens after a pet battle, no combat involved.

**Comment by maQZ89** [comment] 2023-01-10 13:29
Heyho, 
as some others discribed it, it happens for me after a loading screen. Its not all keybinds, but most of them. It's not actionbar related. 
Is there a possible fix or information to fix this? 
I really like Dominos, but its hard to keep using it, if you have to /rl for every dungeon you enter.

**Comment by Tuller** [comment] 2023-01-16 22:13
I'm still having a ton of trouble reproducing this one. At this point, I need people to do the the following:
1. Enable taint logging via `/console taintlog 2` (see https://wowpedia.fandom.com/wiki/CVar_taintLog)
1. When action buttons no longer function, `/console reloadui` as soon as is convienent.
1. Grab the file `taint.log` from the `_retail_\Logs` directory  and attach it here. Please let me know what addons you're running.

**Comment by hollo6** [comment] 2023-01-17 11:19
Just found this:

1/17 12:01:21.068  Execution tainted by Dominos while reading DominosFrameextra - Interface/FrameXML/EditModeSystemTemplates.lua:449 ExtraAbilityContainer:SetSnappedToFrame()
1/17 12:01:21.068      Interface/FrameXML/EditModeSystemTemplates.lua:73
1/17 12:01:21.068      ExtraAbilityContainer:SetPoint()
1/17 12:01:21.068      Interface/AddOns/MoveAnything/Modules/Position.lua:237 RestoreOrgPoints()
1/17 12:01:21.068      Interface/AddOns/MoveAnything/Modules/Position.lua:125 Reset()
1/17 12:01:21.068      Interface/AddOns/MoveAnything/API.lua:327 Reset()
1/17 12:01:21.068      Interface/AddOns/MoveAnything/API.lua:243
1/17 12:01:21.068      xpcall()
1/17 12:01:21.068      Interface/AddOns/MoveAnything/MoveAnything.lua:1303 SyncFrames()
1/17 12:01:21.068      Interface/AddOns/MoveAnything/MoveAnything.lua:1274 SyncAllFrames()
1/17 12:01:21.068      Interface/AddOns/MoveAnything/MoveAnything.lua:5851


Which is curious because I don't even have the ExtraAbility module installed.
I also happen to seem to have a lot less Dominos related taints since I'm not using that module.
Furthermore, MA always causes taint during a pet battle, which, I think, something where that bar is treated differently from every other situation.
All this makes me think that these taints might be related to hiding/showing the ExtraAvility bar.

**Comment by Tuller** [comment] 2023-01-19 22:28
May be worth removing the extra bar from Dominos.toc:
https://github.com/tullamods/Dominos/blob/master/Dominos/Dominos.toc#L37

**Comment by hollo6** [comment] 2023-01-19 22:59
Thanks for the tip!
I have removed that line and also noticed your recent commit for the stance bar and added that too.
Will report if I find anything useful.

**Comment by BlueLemon1** [comment] 2023-01-31 18:17
To add some additional Info from me thus far:
before the patch 10.0.5 : after loading screens, e.g. joining dungeon there was a chance for keybinds no longer working, which got fixed by /reload
After patch 10.0.5: the above did not happen yet to me. But a more serious issue happens. Randomly infight comes the same lua error as before "Actionbar:SetAttribute". But the game is unplayable from then on and the fight is pretty much a wipe. Its huge fps losses and on Shapeshifting as a druid it is a freeze of couple of seconds. I gues because of the pagination of the bars.

So yeah pretty much unplayable so i kinda had to uninstall it.

**Comment by calummitchell** [comment] 2023-03-12 17:23
Uploaded taint.log requested by Tuller.

[taint.zip](https://github.com/tullamods/Dominos/files/10951505/taint.zip)

My addons:
Angry Keystones
BigWigs
BugGrabber
BugSack
ChatCopyPaste
Clique
ColorPickerPlus
Details
Dominos
Doom_CooldownPulse
Grid2
GTFO
idTip_CommunityFork
LeatrixPlus
Lib: SharedMedia-3.0
LittleWigs
Masque
Method Raid Tools
Mythic Dungeon Tools
OmniCD
PasteNG
Plater
Prat
Premade Groups Filter
Quartz
Raider.IO
Raven
RCLootCouncil
SexyMap
SharedMedia
SharedMedia Additional Fonts
SharedMediaAdditionalSounds
Simulationcraft
TomTom
WeakAuras
Bagnon
DejaCharacterStats

**Comment by calummitchell** [comment] 2023-03-28 10:34
Weirdly I seem to only get this error on my hunter and not rogue, druid, shaman, warlock, mage. But it happens on my hunter consistently, so it's easy for me to reproduce. Let me know if you want me to perform any tests. I'm motivated to get this fixed.

**Comment by Aideenwolf** [comment] 2023-06-08 01:44
[taint.log](https://github.com/tullamods/Dominos/files/11682954/taint.log)

Addons:
DBM
WA Soundpack by Causese
AchivementReminder
ArkInvetory
	Config
	Rules
	Search
Astral Keys
Basic ChatMods
Bazooka
	Options
Broker: everything
Broker Mounts
Bug Grabber
Bug Sack
Can I Mog It?
Clique
Details Damage Meter
	Compare 2.0
	Encounter Breakdown
Dominos
	Config
	Progress
Gathermate2
	Data
Handy Notes
	Bfa
	Dragonflight
	Legion
	Mists of Pand
	Shadowlands
	Stygia
	Warlords of dranor
	Wrath of the Litchking
Krow's Achievement Filter
Leatrix plus
Mapster
Masque
Masque: Dominos
Masque: Sleek
Method Raid Tools
Mythic Dungeon tools
Narcissus
oUF
oUF_Drk
Paragon Reputation
Pawn
PetBattleScripts
Platter
Postal
RareScanner
RareTracker
Rarity
Rematch
Routes
SavedInstances
Simulationcraft
Soulbind Conduit Manager
SoundPack
TipTac
TomTom
TullaCC
TullaRange
WeakAuras
WorldQuestList
XLoot
Zereth Mortis Puzzle Helper

**Comment by shengjiex98** [comment] 2023-07-09 00:48
Just to add another data point. I'm experiencing the same issues recently and was able to capture the following log. I reloaded immediately after getting the `Dominos has been blocked from protected function DominosActionButton52:SetAttribute()` error. This happened after using portal to return to Valdrakken from an m+ dungeon.

[taint.log](https://github.com/tullamods/Dominos/files/11994061/taint.log)

My addons are

!BugGrabber
ACU
AdvancedInterfaceOptions
AngryKeystones
BasicMinimap
BasicMinimap_Options
BattleGroundEnemies
BigDebuffs
BigWigs
BigWigs_Aberrus
BigWigs_BattleForAzeroth
BigWigs_Core
BigWigs_DragonIsles
BigWigs_Options
BigWigs_Plugins
BigWigs_VaultOfTheIncarnates
BugSack
Capping
Capping_Options
Coordinates
Details
Details_Compare2
Details_DataStorage
Details_EncounterDetails
Details_RaidCheck
Details_Streamer
Details_TinyThreat
Details_Vanguard
Diminish
Diminish_Options
Dominos
Dominos_Cast
Dominos_Config
Dominos_Progress
Dominos_Roll
eAlignUpdated
HandyNotes
HandyNotes_DragonGlyphs
Leatrix_Plus
LittleWigs
LittleWigs_BattleForAzeroth
LittleWigs_BurningCrusade
LittleWigs_Cataclysm
LittleWigs_Classic
LittleWigs_Legion
LittleWigs_MistsOfPandaria
LittleWigs_Shadowlands
LittleWigs_WarlordsOfDraenor
LittleWigs_WrathOfTheLichKing
LoggerHead
Masque
Masque_Dominos
MistsOfTirnaScitheHelper
MRT
MythicDungeonTools
OmniBar
OmniCC
OmniCC_Config
OmniCD
Plater
Prat-3.0
Prat-3.0_Libraries
RaiderIO
RaiderIO_DB_EU_F
RaiderIO_DB_EU_M
RaiderIO_DB_EU_R
RaiderIO_DB_KR_F
RaiderIO_DB_KR_M
RaiderIO_DB_KR_R
RaiderIO_DB_TW_F
RaiderIO_DB_TW_M
RaiderIO_DB_TW_R
RaiderIO_DB_US_F
RaiderIO_DB_US_M
RaiderIO_DB_US_R
RCLootCouncil
ShadowedUF_Options
ShadowedUnitFrames
SharedMedia
Simulationcraft
TinyTooltip-Reforged
TomCats
TomTom
TradeSkillMaster
TradeSkillMaster_AppHelper
WeakAuras
WeakAurasArchive
WeakAurasModelPaths
WeakAurasOptions
WeakAurasTemplates

**Comment by Neark92** [comment] 2023-09-13 22:02
Is it any solution related to this issue? Kinda sad to uninstall an addon that I have been using for so long

**Comment by Tuller** [comment] 2023-09-13 23:36
The only real solution to the problem is to not use Blizzards code for action buttons. That itself has issues, as click and hold casting is not possible with custom code.

**Comment by gill0n** [comment] 2023-10-28 12:24
> The only real solution to the problem is to not use Blizzards code for action buttons. That itself has issues, as click and hold casting is not possible with custom code.

Without any insight into the cause of the issue and just to confirm my understanding of this; should I take this as 'if you want click and hold casting, and to not have this bug - you have to use vanilla action bars'.

If one is ready to disregard click and hold stuff, I guess there are alternatives out there?

**Comment by Tuller** [comment] 2023-10-28 20:49
Yes, I could simply just write my own action button implementation at that point (this is what Bartender does via LibActionButton).

**Comment by Venkx** [comment] 2023-11-19 09:51
So, the solution could be for you to implement your own action button code for all classes except evokers, and then create "dominos for evokers" with the blizzard code, and everyone who doesn't play evoker wouldn't have that bug anymore?

**Comment by Tuller** [comment] 2023-11-19 16:40
To clarify, I'm talking about the feature where you can hold a hotkey down and it'll continue to cast an ability until you release the key. This is different from the Evoker hold and release to cast different levels of a spell abilities.

**Closed** 2024-01-20 20:13 UTC
Labels: bug, dragonflight
