### ISSUE TITLE
Pet Utility and Call Pet Dropdowns Not Opening on Bars

### ISSUE THREAD

**Issue by storytellersky** [tullamods/Dominos#679] opened 2022-11-14 14:25 UTC
Simple as that

Went to change pets and the drop down for Call Pet did nothing. Tried Pet Utility and it also did nothing. Turned things on and off. Just had dominos running, nothing. Moved the icons/spells out of the spell book and onto the main bars, nothing. Updated to the newest version this morning and still nothing. 

World of Warcraft - Retail

**Comment by Tuller** [comment] 2022-11-14 14:25
This is a duplicate of #678

**Closed by Tuller** 2022-11-14 14:25 UTC
