### ISSUE TITLE
Mage portal and teleport popup list does not show 10.0.0-Alpha4

### ISSUE THREAD

**Issue by jhu54** [tullamods/Dominos#645] opened 2022-10-31 07:51 UTC
Using 10.0.0.0-Alpha4, in any action bar location designated for portals or teleport, pressing the button does not display the list of available locations. The up arrow depicting extra content for the button is displayed.

**Comment by Tuller** [comment] 2022-10-31 11:28
This is a duplicate of #641

**Closed by Tuller** 2022-10-31 11:28 UTC
