### ISSUE TITLE
[ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton33:SetAttribute()'

### ISSUE THREAD

**Issue by 4t0msk** [tullamods/Dominos#779] opened 2023-10-22 00:08 UTC
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton33:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:447: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:513: in function `Update'
[string "@FrameXML/ActionButton.lua"]:465: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:1411: in function <FrameXML/ActionButton.lua:1408>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:266: in function <FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:322: in function <FrameXML/SecureHandlers.lua:306>
[string "=(tail call)"]: ?

**Comment by Tuller** [comment] 2023-11-26 20:24
Duplicate of #620

**Closed by Tuller** 2023-11-26 20:24 UTC
