### ISSUE TITLE
Extra Action Button Broken in 9.0.6

### ISSUE THREAD

**Issue by claycle** [tullamods/Dominos#482] opened 2020-10-21 13:51 UTC
As of the latest Dominos patch, the Extra Action Button has broken. It appears, but it can no longer be activated/clicked on.

Disabling Dominos allows the EAB to be activated.

**Comment by Tuller** [comment] 2020-10-21 13:53
This is a duplicate of https://github.com/tullamods/Dominos/issues/479. Check there

**Comment by claycle** [comment] 2020-10-21 13:59
Not exactly. The button is "gone". It appears. It cannot be activated, though.

**Comment by Tuller** [comment] 2020-10-21 21:26
Is it interactive with other addons disabled? I've been testing this via shadowlands and haven't experienced any issues on my end.

You can also tell dominos to not use the extra bar via `/run Dominos.db.profile.modules.ExtraAbilityBar = false; ReloadUI()`

**Comment by claycle** [comment] 2020-10-22 18:46
I cannot precisely determine which, if any, add-on it might be interacting with (although, frankly, my add-on list is pretty short: Dominos, DBM, RaiderIO, Details, Weakauras, Threatplates). Turning off and reloading the add-ons will often/usually allow the button to function again. However, if it appears (added by a world quest, for example), it will initially not be operable. Reloading, it will be operable.

**Comment by Anduviel** [comment] 2020-10-23 15:20
I had same problem in place I never had it before, waycrest manor last boss the vial of blood, we wiped because we couldn't throw the bottle, whatever I tired didn't work.
reloading didn't help. couldn't test up more tank  ragequit.

**Comment by Tuller** [comment] 2020-10-23 18:40
Is this still happening with 9.0.10?

**Comment by Anduviel** [comment] 2020-10-23 18:42
Haven't tested it agains ory should have said so

**Comment by Vikirnoff** [comment] 2020-10-23 23:59
I am having the same issue. I'm running 9.0.10.

**Comment by arcadepro** [comment] 2020-10-24 00:28
The Extra Action Button does not appear when performing the final stage of the Legion Arms Warrior quest to get Stromkar (Artifact Weapon). When you reach the end of the scenario you are supposed to execute the mob using the extra action button but it does not appear. This is with 9.0.10.

I capped the frame info if its any help. 
![1](https://user-images.githubusercontent.com/1977760/97063534-31398e80-1598-11eb-9d5d-cf99b1fa774d.jpg)

**Comment by Tuller** [comment] 2020-10-24 16:53
One more fixed applied: 'What if i just give the bar a static size?" There's also a binding for the extra action button in Blizzard's binding menu/quick binding mode (which Dominos also supports now)

**Comment by arcadepro** [comment] 2020-10-24 19:35
Tested the above Stromkar issue on PTR with 9.0.11. Still broken. Takes about 20mins to make a new allied race warrior and start the Legion warrior stuff.

Upon triggering the final phase of the scenario you pick up the item (artifact).
When looted, the EAB appears very briefly.
An in game model cinematic plays. (Your toon holding the sword aloft)
On leaving the cinematic there is no EAB.
Reloading the UI now shows the EAB. (which is an improvement over 9.0.10)

This bug will likely most Legion Artifact scenarios.

**Comment by arcadepro** [comment] 2020-10-24 20:12
This Stromkar scenario bug is a Blizzard bug. Retested a couple more times with 0 addons. The EAB is always bugged in this scenario.

Running away and back restores the EAB, or reload UI. The repositioning of the character for the cinematic breaks whatever trigger conditions are required for the EAB.

**Comment by Tuller** [comment] 2020-10-24 20:51
That makes me feel a bit better at least. Its likely due to this in ExtraActionBar.lua
```lua
function ExtraActionBar_OnHide (self)
    ExtraAbilityContainer:RemoveFrame(self);
end
```
That should really be something like this:
```lua
function ExtraActionBar_OnHide (self)
    if HasExtraActionBar() then
        return;
    end

    ExtraAbilityContainer:RemoveFrame(self);
end
```

This script might fix it:
```lua
/run local f = CreateFrame('Frame', nil, nil, 'SecureHandlerBaseTemplate'); f:WrapScript(ExtraActionBarFrame, 'OnHide', 'if HasExtraActionBar() then return false end')
```

**Comment by arcadepro** [comment] 2020-10-24 23:44
Script didn't work.

**Comment by melinerunen** [comment] 2020-10-29 02:33
Well on 9.011 also this bug is present but different!  It appears that after ending combat the button changes its position. I recorded a video with the framestack

https://youtu.be/UsDr0YX7LJ4

**Comment by Vikirnoff** [comment] 2020-10-29 19:30
> 
> 
> Well on 9.011 also this bug is present but different! It appears that after ending combat the button changes its position. I recorded a video with the framestack
> 
> https://youtu.be/UsDr0YX7LJ4

I had a problem like that. I was doing the quest in Azsuna with the little dragon action button. I had to /reload to get the button to show back up and finish the quest. Thanks!

**Comment by OdessaGrimaldus** [comment] 2020-10-29 21:54
Same here, to a smaller extent.

My extra action button is simply not there when entering boss fight combat, like Carapace in Nya'lotha..or here I am doing a extra action button requiring quest out in the world..and the button was there for the first few uses, but I entered combat, only to have it disappear and require a reload of the UI once combat had dropped to return it.

**Comment by Tuller** [comment] 2020-10-29 22:20
@melinerunen 
In that clip, you seem to be using Titan Panel. Titan Panel is known to mess with the extra action button so I would suggest enabling the Disable Screen Adjust option for both the top and bottom bars

**Comment by Tuller** [comment] 2020-10-29 23:29
I've added a workaround for the Titan Panel case. Normally I don't like implementing code for other addons, but enough people have the issue in this case.

**Comment by melinerunen** [comment] 2020-10-30 00:28
@Tuller  Fixed!! Also found that disabling the auto adjust bars speed up the status change on the bars with `[combat]hide;show`

Thanks!!

**Comment by melinerunen** [comment] 2020-10-30 00:34
Tell me if you need to test something else. I would gladly help :)

**Closed** 2020-11-09 13:54 UTC
Labels: ☠️ bug
