### ISSUE TITLE
[ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton4:SetAttribute()'.

### ISSUE THREAD

**Issue by alliepet** [tullamods/Dominos#694] opened 2022-12-02 08:09 UTC
**Addons**
BugSack/Grabber, Details, Dominos, Hide Objectives, MRT, MDT, PetBattleScripts, Rematch, R.IO, SimC, RC Loot Council, Weak Auras, DBM

**Addon Version**
10.0.12-retail

**World of Warcraft Version**
Retail

My BugSack is showing some errors coming from Dominos and I'm not sure why:
`3x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton4:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:412: in function `Update'
[string "@FrameXML/ActionButton.lua"]:362: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:354: in function <FrameXML/ActionButton.lua:353>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:266: in function <FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:430: in function <FrameXML/SecureHandlers.lua:417>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetAttribute'
...
[string "@FrameXML/RestrictedFrames.lua"]:739: in function `RunAttribute'
[string "			self:RunAttribute('updateOverridePage')
		"]:1: in function <[string "			self:RunAttribute('updateOverridePage')..."]:1>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@FrameXML/RestrictedExecution.lua"]:484: in function <FrameXML/RestrictedExecution.lua:447>
[string "=(tail call)"]: ?
[string "@FrameXML/SecureHandlers.lua"]:115: in function <FrameXML/SecureHandlers.lua:110>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/SecureStateDriver.lua"]:114: in function <FrameXML/SecureStateDriver.lua:95>
[string "@FrameXML/SecureStateDriver.lua"]:127: in function <FrameXML/SecureStateDriver.lua:119>`

**Comment by Tuller** [comment] 2022-12-02 23:51
This is a "something is tainting the action button execution path" error. Can you repeat it with just Dominos enabled?

**Comment by jonjbm** [comment] 2022-12-03 05:01
Yes, I just got the following error with nothing other than Dominos, BugGrabber, and BugSack running:

```
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Dominos' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:109: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:14: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR2BUTTON2"]:2: in function <[string "MULTIACTIONBAR2BUTTON2"]:1>
```

I reproduced it by hearthing and then pressing a keybind. Other things sometimes cause it as well. Please fix as soon as possible, it breaks my keybinds entirely until I reload every time it happens.

**Comment by tmgsca** [comment] 2022-12-03 05:05
To add on top of this one, this is the report I captured on BugSack when that same taint happened to me.

This one specifically happened as soon as I was mind-controlled by a rare. Not sure if it is related. I occasionally get this issue while randomly questing.

```
1x [ADDON_ACTION_BLOCKED] AddOn 'Dominos' tried to call the protected function 'DominosActionButton8:SetAttribute()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/ActionButton.lua"]:350: in function `UpdatePressAndHoldAction'
[string "@FrameXML/ActionButton.lua"]:412: in function `Update'
[string "@FrameXML/ActionButton.lua"]:362: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:821: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213> 
```

**Comment by Tuller** [comment] 2023-11-26 20:37
duplicate of 701

**Closed by Tuller** 2023-11-26 20:37 UTC
Labels: bug, dragonflight
