### ISSUE TITLE
Override action bar buttons in new Illidan scenario in Black Rook Hold not showing

### ISSUE THREAD

**Issue by ceylina** [tullamods/Dominos#253] opened 2016-09-11 15:11 UTC
Illidan scenario for blackrook hold opened 9/10 and dominos is not showing them. 

Now when you first start you have a blank override actionbar but as the scenario progresses you get more buttons and those new style annoying info pseudo tooltips show up informing you that you get new buttons.

Dominos does not pick up these buttons when they appear. Granted this is a limited one time scenario so far but I feel they will continue to use this structure going forward and I know from beta that this happens in the other parts of this quest chain.

So the issue is that when you switch to the override bar it is intially blank then you gain buttons as you progress. Dominos is not registering those new buttons you acquire.

**Comment by Zireael-N** [comment] 2016-09-11 20:07
I guess, this is a duplicate of issue #238.

**Comment by Tuller** [comment] 2016-09-11 21:05
Okay, now I've actually had time to look through my code.  What I suspect is happening is that the event UPDATE_OVERRIDE_ACTIONBAR is firing, but ACTIONBAR_SLOT_CHANGED is not, and Dominos only updates a custom override bar if you're not already in combat.

**Comment by ceylina** [comment] 2016-09-11 22:45
I won't be able to confirm this as a fix until the next part of the quest chain but I am pretty confident you know what you are doing ;)

**Comment by Zireael-N** [comment] 2016-09-12 03:29
> you can run /eventtrace and look at the events that pop up

Had to record a video and work with that; there's just way too many events because of NPCs fighting in the background. Uploaded a few screenshots if it helps: https://imgur.com/a/IBm7j

> Or, you can change this bit in bars/actionBar.lua from

Caused an "Interface action failed because of an AddOn" message.

**Comment by Tuller** [comment] 2016-09-12 22:00
Thanks for the info, that's pretty much what I expected and sadly limits the encounter to only working properly when using the blizzard override bar.  I'll try and see if I can come up with a good workaround on the weekend, but at the moment I can't think of anything that doesn't end with me writing my own action button code again :P

**Comment by Tuller** [comment] 2019-05-27 13:13
I think I fixed this one with either the 8.0 or the 8.1 release and failed to close out the issue :P

**Closed by Tuller** 2019-05-27 13:13 UTC
Labels: ☠️ bug
